# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-21 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_item_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.TextField(default='')),
                ('address', models.TextField(default='')),
                ('email', models.EmailField(default='', max_length=254)),
                ('about_description', models.TextField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
