# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-23 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20200621_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='JOB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.TextField(default='')),
                ('company', models.TextField(default='')),
                ('job_description', models.TextField(default='')),
                ('job_dates', models.TextField(default='')),
            ],
        ),
    ]
