# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-23 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWARDS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='EDUCATION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d', models.TextField(default='')),
                ('title', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('grade', models.TextField(default='')),
                ('dates', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='INTERESTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
