# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-23 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_awards_education_interests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='d',
            new_name='institution',
        ),
    ]
