# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-24 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_auto_20200623_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_dates',
            new_name='dates',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_title',
            new_name='title',
        ),
    ]
